app:
  name: "foodcook"
  version: "1.0.0"
  port: 8080
  mode: "debug" # debug, release

database:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  name: "foodcook"
  charset: "utf8mb4"
  parse_time: true
  loc: "Local"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 10

jwt:
  secret: "your-secret-key-change-in-production"
  expire_hours: 24

upload:
  max_size: 10485760 # 10MB
  allowed_types: ["image/jpeg", "image/png", "image/gif"]
  upload_path: "./uploads"

cors:
  allowed_origins: ["http://localhost:3000", "http://localhost:5173"]
  allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowed_headers: ["*"]
  allow_credentials: true 